# MODEL TRAINIG

Import Data and Required Packages

In [35]:
#Basic Imports
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

#Modeling
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

# Import CSV Data and Pandas DataFrame

In [6]:
df = pd.read_csv('health_data.csv')

In [7]:
df.head()

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence

In [8]:
le = LabelEncoder()

In [10]:
df['Heart Disease'] = le.fit_transform(df['Heart Disease'])

In [12]:
df.head()

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,1
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,0
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,1
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,0
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,0

# Preparing X and y vairibles

In [13]:
X = df.drop(columns=['Heart Disease'],axis=1)

In [14]:
X.head()

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3

In [19]:
y = df['Heart Disease']

In [20]:
y

0      1
1      0
2      1
3      0
4      0
      ..
265    0
266    0
267    0
268    0
269    1
Name: Heart Disease, Length: 270, dtype: int64

Create Column Transformer

In [29]:
num_features = X.select_dtypes(exclude="object").columns

numeric_transformer = StandardScaler()

preprocessor = ColumnTransformer(
    [
         ("StandardScaler", numeric_transformer, num_features),        
    ]
)

In [30]:
X = preprocessor.fit_transform(X)

In [32]:
X.shape

(270, 13)

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
X_train.shape, X_test.shape

((216, 13), (54, 13))

Create an Evalute Function to give all metrics after model trainig

In [41]:
def evaluate_model(true, predicted):
    acc = accuracy_score(true, predicted)
    prec = precision_score(true, predicted)
    rec = recall_score(true, predicted)
    conf = confusion_matrix(true, predicted)
    return acc, prec, rec, conf

In [42]:
models = {
    'Logistic Regression':LogisticRegression(),
    'DecisionTree Classifier':DecisionTreeClassifier(),
    'RandomForest Classifier':RandomForestClassifier(),
    'KNeighbors Classifier': KNeighborsClassifier(),
    'XGBClassifier': XGBClassifier()        
} 



model_list = []
acc_list = []

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    # Evaluate Train and Test dataset
    model_train_acc , model_train_prec, model_train_rec, model_train_conf = evaluate_model(y_train, y_train_pred)

    model_test_acc , model_test_prec, model_test_rec, model_test_conf = evaluate_model(y_test, y_test_pred)
    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model performance for Training set')
    print("- Accuracy Score : {:.4f}".format(model_train_acc))
    print("- Precision Score: {:.4f}".format(model_train_prec))
    print("- Recall Score: {:.4f}".format(model_train_rec))
    print("- Confusion Matrix:" ,model_train_conf)

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Accuracy Score : {:.4f}".format(model_test_acc))
    print("- Precision Score: {:.4f}".format(model_test_prec))
    print("- Recall Score: {:.4f}".format(model_test_rec))
    print("- Confusion Matrix:" ,model_test_conf)
    acc_list.append(model_test_acc)
    
    print('='*35)
    print('\n')

Logistic Regression
Model performance for Testing set
- Accuracy Score : 0.8380
- Precision Score: 0.8333
- Recall Score: 0.8081
- Confusion Matrix: [[101  16]
 [ 19  80]]
----------------------------------
Model performance for Test set
- Accuracy Score : 0.9074
- Precision Score: 0.9000
- Recall Score: 0.8571
- Confusion Matrix: [[31  2]
 [ 3 18]]
===================================


DecisionTree Classifier
Model performance for Testing set
- Accuracy Score : 1.0000
- Precision Score: 1.0000
- Recall Score: 1.0000
- Confusion Matrix: [[117   0]
 [  0  99]]
----------------------------------
Model performance for Test set
- Accuracy Score : 0.6667
- Precision Score: 0.5556
- Recall Score: 0.7143
- Confusion Matrix: [[21 12]
 [ 6 15]]
===================================


RandomForest Classifier
Model performance for Testing set
- Accuracy Score : 1.0000
- Precision Score: 1.0000
- Recall Score: 1.0000
- Confusion Matrix: [[117   0]
 [  0  99]]
----------------------------------
Model performance for Test set
- Accuracy Score : 0.8704
- Precision Score: 0.9375
- Recall Score: 0.7143
- Confusion Matrix: [[32  1]
 [ 6 15]]
===================================


KNeighbors Classifier
Model performance for Testing set
- Accuracy Score : 0.8565
- Precision Score: 0.8542
- Recall Score: 0.8283
- Confusion Matrix: [[103  14]
 [ 17  82]]
----------------------------------
Model performance for Test set
- Accuracy Score : 0.8148
- Precision Score: 0.8235
- Recall Score: 0.6667
- Confusion Matrix: [[30  3]
 [ 7 14]]
===================================


XGBClassifier
Model performance for Testing set
- Accuracy Score : 1.0000
- Precision Score: 1.0000
- Recall Score: 1.0000
- Confusion Matrix: [[117   0]
 [  0  99]]
----------------------------------
Model performance for Test set
- Accuracy Score : 0.8148
- Precision Score: 0.7895
- Recall Score: 0.7143
- Confusion Matrix: [[29  4]
 [ 6 15]]
===================================

In [46]:
pd.DataFrame(list(zip(model_list, acc_list)), columns=['Model Name', 'Accuracy_Score']).sort_values(by=["Accuracy_Score"],ascending=False)

                Model Name  Accuracy_Score
0      Logistic Regression        0.907407
2  RandomForest Classifier        0.870370
3    KNeighbors Classifier        0.814815
4            XGBClassifier        0.814815
1  DecisionTree Classifier        0.666667

# Logistic Regression

In [48]:
lin_model = LogisticRegression(fit_intercept=True)
lin_model = lin_model.fit(X_train, y_train)
y_pred = lin_model.predict(X_test)
score = accuracy_score(y_test, y_pred)*100
print(" Accuracy of the model is %.2f" %score)

 Accuracy of the model is 90.74